@startuml

/'
    注解：元注解
    @Retention注解时机
    @Target注解位置
    @Inherited 是否允许子类集成

    反射：
    1.获取class类 Class.forName(package + class name);
    2.创建class实例对象 class.newInstance();
    3.根据实例获取类 clazz.getClass();
    4.获取类定义的属性 class.getDeclaredFields();
    5.获取类定义的方法 class.getMethods();
    6.调用方法 method.invoke(a, args[])
    7.获取请求路径 request.getRequestURI()
'/


:扫描项目.class文件目录;
:把类名储存到Map容器中;
:根据不同注解实例化类并存储到Map中;
:把对象动态注入到成员变量中;
:把url路径和方法做映射;
stop

:获取请求路径;
:查出路径对应的方法;
:获取方法中的参数;
:通过方法中的参数名解析请求中的参数值;
:动态方法调用;
stop



@enduml